[package]
name = "rustrict_devzat"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustrict_devzat"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
rustrict = "0.7.8"
libc = "0.2.0"

